=pod

=head1 NAME

/etc/dnsval.conf, /etc/resolv.conf, /etc/root.hints - Configuration policy for the DNSSEC validator library libval(3).
val_add_valpolicy - Dynamically add a new policy to the validator context
val_remove_valpolicy - Remove a dynamically added policy from the validator context

=head1 SYNOPSIS

    int val_add_valpolicy(val_context_t *context, const char *keyword,
                    char *zone, char *value, long ttl,
                    val_policy_entry_t **pol);

    int val_remove_valpolicy(val_context_t *context, 
                    val_policy_entry_t *pol);

=head1 DESCRIPTION

Applications can use local policy to influence the validation outcome.
Examples of local policy elements include trust anchors for different zones
and untrusted algorithms for cryptographic keys and hashes.  Local policy
may vary for different applications and operating scenarios.

The I<val_add_valpolicy()> function can be used to dymanically add a new policy
for a given context. The I<keyword>, I<zone> and I<value> arguments are
identical to I<KEYWORD>, I<zone> and I<additional-data> defined below for 
B</etc/dnsval.conf>. I<ttl> specifies the duration in seconds for which the 
policy is kept in effect. A value of B<-1> adds to policy to the context 
indefinitely. A handle to the newly added policy is returned in I<*pol>.  
This structure is opaque to the applications; applications must not modify the 
contents of the memory returned in I<*pol>. 

Applications may also revoke the effects of a newly added policy, I<pol>, 
before the expiry of its timeout interval using the 
I<val_remove_valpolicy()> policy. 

The validator library reads configuration information from three separate
files, B</etc/resolv.conf>, B</etc/root.hints>, and B</etc/dnsval.conf>.

=over 4

=item /etc/resolv.conf

The I<nameserver> and I<search> options are supported in the B<resolv.conf> file.

This I<nameserver> option is used to specify the IP address of the name server to which
queries must be sent by default.  For example,

    nameserver 10.0.0.1

This I<search> option is used to specify the search path for issuing queries. For example, 

    search test.dnssec-tools.org dnssec-tools.org 

If the B</etc/resolv.conf> file contains no name servers, the validator 
tries to recursively answer the query using information present
in B</etc/root.hints>.

=item /etc/root.hints

The B</etc/root.hints> file contains bootstrapping information for the
resolver while it attempts to recursively answer queries.  The contents of
this file may be generated by the following command:

    dig @e.root-servers.net . ns > root.hints

=item /etc/dnsval.conf

The B</etc/dnsval.conf> file contains the validator policy. It consists of 
a sequence of the following "policy-fragments":

    <label> <KEYWORD> <zone> <additional-data> [<zone> <additional-data> ]; 

Policies are identified by simple text strings called
labels, which must be unique within the configuration system.  For example,
"browser" could be used as the label that defines the validator policy for all
web-browsers in a system.  A label value of ":" identifies the default policy,
the policy that is used when a NULL context is specified as the I<ctx>
parameter for interfaces listed in I<libval(3)>,
I<val_getaddrinfo(3)>, and I<val_gethostbyname(3)>. The default policy is
unique within the configuration system.

I<KEYWORD> is the specific policy component that is specified within the 
policy fragment. The format of I<additional-data> depends on the 
keyword specified.

If multiple policy fragments are defined for the same label and keyword
combination then the last definition in the file is used.

The following keywords are defined for B<dnsval.conf>:

=over 4

=item trust-anchor

Specifies the trust anchors for a sequence of zones.  The additional
data portion for this keyword is a quoted string containing the 
RDATA portion for the trust anchor's DNSKEY.

=item zone-security-expectation

Specifies the local security expectation for a zone.  The additional
data portion for this keyword is the zone's trust status - 
ignore, validate, trusted, or untrusted. The default zone security
expectation is validate.

=item provably-unsecure-status 

Specifies if the provably unsecure condition must be considered as 
trusted or not. The additional data portion for this keyword is the 
trust status for the provably unsecure condition for a given zone - 
trusted, or untrusted. The default provably unsecure status is trusted.

=item clock-skew 

Specifies how many seconds of clock skew is acceptible when verifying 
signatures for data from a given zone. The additional data portion 
for this keyword is the number of seconds of clock skew that is
acceptible. A value of -1 completely ignores inception and expiration times 
on signatures for data from a given zone. The default clock skew is 0.

=item nsec3-max-iter [only if LIBVAL_NSEC3 is enabled]

Specifies the maximum number of iterations allowable while computing
the NSEC3 hash for a zone. A value of -1 does not place a maximum limit on
the number of iterations. This is also the default setting for a zone.

=item dlv-trust-points [only if LIBVAL_DLV is enabled]

Specifies the dlv tree for the target zone. 

=back

=back

=head1 EXAMPLE

The B</etc/dnsval.conf> configuration file might appear as follows:

=over 4

=item : trust-anchor

=over 4

=item dnssec-tools.org.

=over 4

=item "257 3 5 AQO8XS4y9r77X9SHBmrxMoJf1Pf9AT9Mr/L5BBGtO9/e9f/zl4FFgM2l B6M2XEm6mp6mit4tzpB/sAEQw1McYz6bJdKkTiqtuWTCfDmgQhI6/Ha0 EfGPNSqnY 99FmbSeWNIRaa4fgSCVFhvbrYq1nXkNVyQPeEVHkoDNCAlr qOA3lw=="

=back

=item netsec.tislabs.com.

=over 4

=item "257 3 5 AQO8XS4y9r77X9SHBmrxMoJf1Pf9AT9Mr/L5BBGtO9/e9f/zl4FFgM2l B6M2XEm6mp6mit4tzpB/sAEQw1McYz6bJdKkTiqtuWTCfDmgQhI6/Ha0 EfGPNSqnY 99FmbSeWNIRaa4fgSCVFhvbrYq1nXkNVyQPeEVHkoDNCAlr qOA3lw==" 

=back

=item ;

=back

=item browser zone-security-expectation    

=over 4

=item org ignore 

=item net ignore

=item dnssec-tools.org validate

=item com ignore

=item ;

=back

=item : provably-unsecure-status 

=over 4

=item . trusted 

=item net untrusted

=item ;

=back

=item mta clock-skew 

=over 4

=item . 0 

=item fruits.netsec.tislabs.com. -1

=item ;

=back

=item : nsec3-max-iter 

=over 4

=item . 30

=item ;

=back

=item browser dlv-trust-points 

=over 4

=item . dlv.isc.org

=item ;

=back

=back

=head1 FILES

/etc/resolv.conf

/etc/root.hints

/etc/dnsval.conf	The libval(3) configuration files.

=head1 COPYRIGHT

Copyright 2004-2007 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the dnssec-tools package for details.

=head1 SEE ALSO

B<libval(3)>

http://dnssec-tools.sourceforge.net

=cut	
