
=pod

=head1 NAME

B<libval_check_conf> - command-line program for checking validity of the
validator configuration files.

=head1 SYNOPSIS

    libval_check_conf [options]

=head1 DESCRIPTION

This program checks a given validator configuration file for any syntax errors. 
If no file is specified as a command line option, the default B<dnsval.conf> 
file is checked.

=head1 RETURN VALUES

The program returns 0 on success and -1 on failure.

=head1 OPTIONS

=over

=item -d, --dnsval-conf

Specifies the location for the dnsval.conf file.  If this option is not
specified the default dnsval.conf file recognized by the validator library is
used instead.

=item -r, --resolv-conf

Specifies the location for the resolv.conf file.  If this option is not
specified the default resolv.conf file recognized by the validator library is
used instead.

=item -i, --root-hints

Specifies the location for the root.hints file.  If this option is not
specified the default root.hints file recognized by the validator library is
used instead.

=item -v, --verbose

Displays detailed messages and warnings associated with the validator configuration file check process.

=item -h, --help

Displays a usage help message and exits the program.

=back

=head1 COPYRIGHT

Copyright 2005-2012 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the DNSSEC-Tools package for details.

=head1 AUTHORS

Suresh Krishnaswamy (suresh@tislabs.com)

=head1 SEE ALSO

B<dnsval.conf(3)>

=cut
