=pod

=head1 NAME

val_getaddrinfo, val_freeaddrinfo - get DNSSEC-validated network address
and service translation

=head1 SYNOPSIS

  #include <validator.h>

  int val_getaddrinfo(const struct val_context *ctx,
                      const char *nodename,
                      const char *servname,
                      const struct addrinfo *hints,
                      struct val_addrinfo **res);

  void val_freeaddrinfo(struct val_addrinfo *ainfo);

=head1 DESCRIPTION

I<val_getaddrinfo()> performs DNSSEC validation of DNS queries.  It
is intended to be a DNSSEC-aware replacement for I<getaddrinfo(3)>.  It
I<val_getaddrinfo()> is a DNSSEC-aware function intended as a replacement
for I<getaddrinfo(3)>.  It performs DNSSEC validation of DNS queries.  It
returns a network address value of type I<struct val_addrinfo> in the I<res>
parameter.

  struct val_addrinfo {
          int ai_flags;
          int ai_family;
          int ai_socktype;
          int ai_protocol;
          size_t ai_addrlen;
          struct sockaddr *ai_addr;
          char * ai_canonname;
          struct val_addrinfo *ai_next;
          val_status_t         ai_val_status;
  };

The I<val_addrinfo> structure is similar to the I<addrinfo> structure
(described in I<getaddrinfo(3)>).  I<val_addrinfo> has an additional field
I<ai_val_status> that represents the validation status for that particular
record.  I<val_istrusted()> determines whether this validation status
represents a trusted value and I<p_val_status()> displays this value to the
user in a useful manner.  (See I<libval(3)> for more information).

The I<ctx> parameter of type I<val_context> represents the validation context,
which can be NULL for default value.  The caller can use this parameter to
control the resolver and validator policies used during validation.
(See I<libval(3)> for information on creating a validation context.)

The I<nodename>, I<servname>, and I<hints> parameters are similar in
meaning and syntax as the corresponding parameters for the original
I<getaddrinfo()> function.  The I<res> parameter is similar to the
I<res> parameter for I<getaddrinfo()>, except that it is of type
I<struct val_addrinfo> instead of I<struct addrinfo>.  Please see the manual
page for I<getaddrinfo(3)> for more details about these parameters.

I<val_freeaddrinfo()> frees the memory allocated for a I<val_addrinfo> linked
list.

=head1 RETURN VALUES

The I<val_getaddrinfo()> function returns 0 on success and a non-zero error
code on failure.  I<*res> will point to a dynamically allocated linked list
of I<val_addrinfo> structures on success and will be NULL on error.
The memory for the value returned in I<*res> can be released using
I<val_freeaddrinfo()>.

=head1 EXAMPLE

 #include <stdio.h>
 #include <stdlib.h>
 #include <validator.h>

 int main(int argc, char *argv[])
 {
          struct val_addrinfo *ainfo = NULL;
          int retval;

          if (argc < 2) {
                  printf("Usage: %s <hostname>\n", argv[0]);
                  exit(1);
          }
 
          retval = val_getaddrinfo(NULL, argv[1], NULL, NULL, &ainfo);

          if ((retval == 0) && (ainfo != NULL)) {

                  printf("Validation Status = %d [%s]\n",
                         ainfo->ai_val_status,
                         p_val_status(ainfo->ai_val_status));

                  val_freeaddrinfo(ainfo);
          }

          return 0;
 }

=head1 COPYRIGHT

Copyright 2004-2006 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the DNSSEC-Tools package for details.

=head1 AUTHORS

Abhijit Hayatnagarkar

=head1 SEE ALSO

I<getaddrinfo(3)>

I<val_gethostbyname(3)>, I<val_query(3)>

I<libval(3)>

http://dnssec-tools.sourceforge.net

=cut
