Document: lookup
Title: Debian lookup Manual
Author: <insert document author here>
Abstract: This manual describes what lookup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lookup/lookup.sgml.gz

Format: postscript
Files: /usr/share/doc/lookup/lookup.ps.gz

Format: text
Files: /usr/share/doc/lookup/lookup.text.gz

Format: HTML
Index: /usr/share/doc/lookup/html/index.html
Files: /usr/share/doc/lookup/html/*.html

  
