--- Makefile.orig	2007-08-27 12:26:31.000000000 -0400
+++ Makefile	2007-08-27 14:39:59.000000000 -0400
@@ -237,6 +237,7 @@
 	${EXTRA_CRYPTO_DEFS} \
 	$(HAVE_THREADS_DEFS) \
 	$(SMARTCARD_DEFS) \
+	-DDNSSEC_LOCAL_VALIDATION -DADNS_THREADS \
 	-DPLUTO \
 	-DKLIPS \
         -DBUILDER=\"${BUILDER}\" \
@@ -272,7 +273,7 @@
 endif
 
 LIBSADNS = $(OPENSWANLIB)
-LIBSADNS += -lresolv # -lefence
+LIBSADNS += -lpthread -lval-threads -lsres -lcrypto # -lefence
 
 # Solaris needs -lsocket -lnsl
 LIBSWHACK = whacklib.o ${OPENSWANLIB} 
