#
# Minimum environment and virtual path setup
#
SHELL           = /bin/sh
srcdir          = @srcdir@
top_srcdir      = @top_srcdir@
top_builddir    = @top_builddir@
@SET_MAKE@

#
# Paths
#
prefix		= @prefix@
exec_prefix	= @exec_prefix@
bindir		= @bindir@
sbindir		= @sbindir@
libdir		= @libdir@
datadir		= @datadir@
includedir	= @includedir@
mandir		= @mandir@
man1dir		= $(mandir)/man1
man3dir		= $(mandir)/man3
man5dir		= $(mandir)/man5
man8dir		= $(mandir)/man8

#
# compilation parameters
#
CC=@CC@
CFLAGS_EX=
CFLAGS=@CFLAGS@ $(CFLAGS_EX)
LDFLAGS_EX=
LDFLAGS=@LDFLAGS@ $(LDFLAGS_EX)
AR=@AR@
RANLIB=@RANLIB@
RM=@RM@
INSTALL=@INSTALL@

LIBTOOL=@LIBTOOL@
LIBTOOLCC=$(LIBTOOL) --mode=compile $(CC) $(CFLAGS)
LIBTOOLLD=$(LIBTOOL) --mode=link $(CC) $(CFLAGS) -rpath $(libdir)
LIBTOOLIN=$(LIBTOOL) --mode=install $(INSTALL)
LIBTOOLFN=$(LIBTOOL) --mode=finish $(libdir)
