.TH DNSSEC_NODES 1 "26 Oct 2011" "User Commands"
.UC 5
.SH NAME
dnssec-nodes \- A graphical DNS visualization tool
.SH DESCRIPTION
A graphical DNS visualization application, specializing in DNSSEC.
The DNSSEC-Nodes application is a graphical debugging utility that
allows administrators to watch the data being logged into a libval or
bind logging file.
.PP
Further information on this tool can be found on the DNSSEC-Tools wiki
page, of which this application is a component:
.IP
http://www.dnssec-tools.org/wiki/index.php/DNSSEC-Nodes
.SH "SEE ALSO"
For more information on the DNSSEC-Tools project, see the project's
web page:
.IP
http://www.dnssec-tools.org/
.SH "LICENSE"
The DNSSEC-Tools are licensed under a BSD license, the details of
which can be found in the COPYING file found within the distribution.

