.TH DNSSEC_NODES 1 "26 Oct 2011" "User Commands"
.UC 5
.SH NAME
dnssec-check \- A tool to check DNSSEC capabilities of the local DNS resolvers
.SH DESCRIPTION
DNSSEC-Check provides a GUI mechansim for scanning the system's
configured DNS resolvers to see if they support DNSSEC.  For each test
the utility displays a graphical red/green light indicating the result
of the test.  Clicking on a light will explain the status of the light
and what was tested.
.PP
Further information on this tool can be found on the DNSSEC-Tools wiki
page, of which this application is a component:
.IP
http://www.dnssec-tools.org/wiki/index.php/DNSSEC-Check
.SH "SEE ALSO"
For more information on the DNSSEC-Tools project, see the project's
web page:
.IP
http://www.dnssec-tools.org/
.SH "LICENSE"
The DNSSEC-Tools are licensed under a BSD license, the details of
which can be found in the COPYING file found within the distribution.

