=pod

=head1 NAME

val_gethostbyname, val_x_gethostbyname, val_get_hostent_dnssec_status, val_duphostent, val_freehostent - get DNSSEC-validated network host entry

=head1 SYNOPSIS

  #include <validator.h>

  struct hostent *val_gethostbyname(const char *name, int *h_errnop);

  struct hostent *val_x_gethostbyname(const val_context_t *ctx,
                                      const char *name, int *h_errnop);

  int val_get_hostent_dnssec_status(const struct hostent *hentry);

  struct hostent* val_duphostent(const struct hostent *hentry);

  void val_freehostent(struct hostent *hentry);

=head1 DESCRIPTION

B<val_gethostbyname()> is a DNSSEC-aware, thread-safe version of
B<gethostbyname(3)>.  It performs DNSSEC validation of DNS queries.
It returns a network host entry value of type I<hostent>.  (See
B<gethostbyname(3)> for more information on type I<hostent>).

B<val_x_gethostbyname()> performs the same function as B<val_gethostbyname()>,
but it optimized for multiple calls.  The two routines take the same
parameters, but B<val_x_gethostbyname()> takes an additional parameter I<ctx>,
of type I<val_context>, which passes the validation context for use in call
optimization.  The I<ctx> parameter also gives the caller more control over
the resolver and validator policies.  If a B<NULL> value is passed for the
I<ctx> parameter, the default validation context is used.  (See
B<get_context()> for information on creating a validation context.)
B<val_gethostbyname()> is equivalent to calling B<val_x_gethostbyname()>
with a B<NULL> I<ctx> parameter.

I<h_errnop> returns the I<h_errno> value from these functions.  This ensures
thread safety, by avoiding the global I<h_errno> variable.  I<h_errnop> must
not be B<NULL>.  (See the man page for B<gethostbyname(3)> for possible values
of I<h_errno>.)

B<val_duphostent()> provides a way to duplicate the I<hostent> structure and
its auxiliary data.  It performs a deep copy; i.e., the internal strings and
arrays are also copied.

B<val_freehostent()> is used to free the hostent structure returned by the
B<val_gethostbyname()>, B<val_x_gethostbyname()> and B<val_duphostent()>
functions.

B<val_get_hostent_dnssec_status()> is used to extract the DNSSEC
validation status from the returned I<hostent> structure.  This function
must be called only for the values returned from B<val_gethostbyname()>,
B<val_x_gethostbyname()>, and B<val_duphostent()> functions.

=head1 RETURN VALUE

The B<val_gethostbyname()> and B<val_x_gethostbyname()> functions return a
value of type I<hostent> on success, and B<NULL> on error.  The memory for
the returned value is dynamically allocated by these two functions.  Hence,
the caller must only call the B<val_freehostent()> function on the returned
value in order to avoid memory leaks.

The B<val_get_hostent_dnssec_status()> function returns the result of the
DNSSEC validation.  The possible values for the DNSSEC status are given in
B<val_errors.h>.

The B<val_duphostent()> function returns a copy of specified the I<hostent>
structure.  The returned value must be freed using B<val_freehostent()> to
avoid memory leaks.

=head1 EXAMPLE
 
 #include <stdio.h>
 #include <validator.h>
 
 int main(int argc, char *argv[])
 {
          int dnssec_status = ERROR;
          int val_h_errno = NETDB_INTERNAL;
          struct hostent *h = NULL;

          if (argc < 2) {
                  printf("Usage: %s <hostname>\n", argv[0]);
                  exit(1);
          }
 
          h = val_gethostbyname(argv[1], &val_h_errno);
          printf("h_errno = %d [%s]\n", val_h_errno,
                 hstrerror(val_h_errno));
          if (h) {
                  dnssec_status = val_get_hostent_dnssec_status(h);

                  printf("DNSSEC Status = %d [%s]\n", dnssec_status,
                         p_val_error(dnssec_status));
                  val_freehostent(h);
          }

          return 0;
 }

=head1 NOTES

This version of B<val_x_gethostbyname()> hence B<val_gethostbyname()> does
not read the order-of-look-up method from B</etc/hosts.conf>.  This
functionality will be provided in future versions.  At present, the default
order is set to consult the B</etc/hosts> file first, and then query DNS.

This version of B<val_x_gethostbyname()> and B<val_gethostbyname()> does not
support NIS lookups.

=head1 COPYRIGHT

Copyright 2004-2005 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the DNSSEC-Tools package for details.

=head1 AUTHORS

Abhijit Hayatnagarkar, Suresh Krishnaswamy.

=head1 SEE ALSO

B<getaddrinfo>(3)

B<get_context(3)>, B<val_dupaddrinfo(3)>, B<val_freeaddrinfo(3)>,
B<val_getaddrinfo(3)>, B<val_query(3)>, B<val_x_getaddrinfo(3)>,
B<val_x_query(3)>

I<p_val_error>

http://dnssec-tools.sourceforge.net

=cut
