#
# Copyright 2004-2006 SPARTA, Inc.  All rights reserved.  See the COPYING
# file distributed with this software for details
#
# DNSSEC Tools
#
#	Keyrec file format.
#

1;

#############################################################################

=pod

=head1 NAME

B<keyrec> - Zone and key data used by DNSSEC-Tools programs.

=head1 DESCRIPTION

I<keyrec> files contain data about zones signed by and keys generated by the
DNSSEC-Tools programs.  A I<keyrec> file is organized in sets of I<keyrec>
records.  Each I<keyrec> must be either of I<zone> type, I<set> type, or
I<key> type.
Zone I<keyrec>s describe how the zones were signed.
Set I<keyrec>s describe sets of key I<keyrec>s.
Key I<keyrec>s describe how encryption keys were generated.
A I<keyrec> consists of a set of keyword/value entries.

The DNSSEC-Tools B<keyrec.pm> module manipulates the contents of a I<keyrec>
file.  Module interfaces exist for looking up I<keyrec> records, creating
new records, and modifying existing records.

Comment lines and blank lines are ignored by the DNSSEC-Tools programs.
Comment lines start with either a '#' character or a ';' character.

=head1 FIELDS

The fields in a I<keyrec> record are described in this section.  The fields
in each type of record (zone, set, key) are described in their own subsection.

=head2 Zone Keyrec Fields

 * zonefile

The name of the zone file for this zone.

 * signedfile

The name of the signed zone file for this zone.

 * endtime

The time when the zone's SIG records expire.  This field is passed to
B<dnssec-signzone> as the argument to the I<-e> option.

 * kskkey

The name of the zone's KSK key.  This is used as the name of the KSK key's
I<keyrec> field.

 * kskpath

The path to the zone's KSK key.  This may be an absolute or relative path,
but it should be one which B<zonesigner> may use (in conjunction with other
I<keyrec> fields to find the key.

 * kskdirectory

The directory that holds the KSK key.

 * zskcur

The name of the signing set for the current ZSK keys.
This is the name of the signing set's set I<keyrec>.

 * zskpub

The name of the signing set for the current ZSK keys.
This is the name of the signing set's set I<keyrec>.

 * zsknew

The name of the signing set for the current ZSK keys.
This is the name of the signing set's set I<keyrec>.

 * keyrec_signsecs

The numeric timestamp of the zone I<keyrec>'s last update.
This is measured in seconds since the epoch.

 * keyrec_signdate

The textual timestamp of the zone I<keyrec>'s last update.
This is a translation of the I<keyrec_signsecs> field.

=head2 Set Keyrec Fields

 * zonename

The name of the zone for which this signing set was generated.

 * keys

The list of keys in this signing set.  Each key listed should have a
corresponding key I<keyrec> whose name matches the key name.

 * keyrec_setsecs

The numeric timestamp of the signing set's creation.
This is measured in seconds since the epoch.

 * keyrec_setdate

The textual timestamp of the signing set's creation.
This is a translation of the I<keyrec_setsecs> field.

=head2 Key Keyrec Fields

 * zonename

The name of the zone for which this key was generated.

 * algorithm

The encryption algorithm used to generate this key.

 * random

The random number generator used to generate this key.

 * keypath

The path to the key.  This may be an absolute or relative path, but it should
be one which B<zonesigner> may use (in conjunction with other I<keyrec>
fields to find the key.

 * ksklength

The length of a KSK key.  This is only included in I<keyrec>s for KSK keys.

 * zsklength

The length of a ZSK key.  This is only included in I<keyrec>s for ZSK keys.

 * keyrec_gensecs

The numeric timestamp of the key's creation.  This is measured in seconds
since the epoch.

 * keyrec_gendate

The textual timestamp of the key's creation.  This is a translation of
the I<keyrec_gensecs> field.

=head1 EXAMPLES

The following is an example of a zone I<keyrec>:

    zone        "example.com"
            zonefile        "db.example.com"
            signedfile      "db.example.com.signed"
            endtime         "+604800"
            kskkey          "Kexample.com.+005+33333"
            kskpath         "keydir/Kexample.com.+005+33333"
            kskdirectory    "keydir"
            zskcur          "signing-set-42"
            zskpub          "signing-set-43"
            zsknew          "signing-set-44"
            keyrec_signsecs "1123771721"
            keyrec_signdate "Thu Aug 11 14:48:41 2005"

The following is an example of a set I<keyrec>:

    set        "signing-set-42"
            zonename        "example.com"
            keys            "Kexample.com.+005+88888"
            keyrec_setsecs  "1123771350"
            keyrec_setdate  "Thu Aug 11 14:42:30 2005"

The following is an example of a key I<keyrec>:

    key        "Kexample.com.+005+88888"
            zonename        "example.com"
            algorithm       "rsasha1"
            random          "/dev/urandom"
            keypath         "./Kexample.com.+005+88888.key"
            ksklength       "1024"
            keyrec_gensecs  "1123771354"
            keyrec_gendate  "Thu Aug 11 14:42:34 2005"

=head1 COPYRIGHT
                 
Copyright 2004-2006 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the DNSSEC-Tools package for details.

=head1 AUTHOR

Wayne Morrison, tewok@users.sourceforge.net

=head1 SEE ALSO

B<lskrf(1)>

B<dnssec-signzone(8)>,
B<signset-editor(8)>,
B<zonesigner(8)>

B<Net::DNS::SEC::Tools::keyrec(3)>

=cut
