#
# Minimum environment and virtual path setup
#
SHELL           = @SHELL@
srcdir          = @srcdir@
top_srcdir      = @top_srcdir@
top_builddir    = @top_builddir@
@SET_MAKE@

#
# Paths
#
prefix		= @prefix@
exec_prefix	= @exec_prefix@
sysconfdir	= @sysconfdir@
bindir		= @bindir@
sbindir		= @sbindir@
libdir		= @libdir@
datarootdir	= @datarootdir@
datadir		= @datadir@
includedir	= @includedir@/validator
mandir		= @mandir@
man1dir		= $(mandir)/man1
man3dir		= $(mandir)/man3
man5dir		= $(mandir)/man5
man8dir		= $(mandir)/man8
CONFIG_CACHE_FILE = @CONFIG_CACHE_FILE@

#
# compilation parameters
#
CC=@CC@
DEVCFLAGS=@DEVFLAGS@
CFLAGS_EX=
CFLAGS=@CFLAGS@ $(DEVCFLAGS) $(CFLAGS_EX)
CPPFLAGS=@CPPFLAGS@
LDFLAGS_EX=
LDFLAGS=@LDFLAGS@ $(LDFLAGS_EX)
AR=@AR@
RANLIB=@RANLIB@
RM=@RM@
CP=@CP@
INSTALL=@INSTALL@
DOCINSTALL=$(INSTALL) -m 644
MKPATH=$(top_srcdir)/mkinstalldirs
EXEEXT=@EXEEXT@

VAL_RESOLV_CONF=@VAL_RESOLV_CONF@
VAL_ROOT_HINTS=@VAL_ROOT_HINTS@
VAL_CONFIGURATION_FILE=@VAL_CONFIGURATION_FILE@

# suffix, if any (eg '-threads')
LIBVAL_SUFFIX=@LIBVAL_SUFFIX@

# use libtool versioning the way they recommend.
# The (slightly clarified) rules stolen from Net-SNMP:
#
# - If any interfaces/structures have been removed or changed since the
#   last update, increment current, and set age and revision to 0. Stop.
#
# - If any interfaces have been added since the last public release, then
#   increment current and age, and set revision to 0. Stop.
# 
# - If the source code has changed at all since the last update,
#   then increment revision (c:r:a becomes c:r+1:a). 
#
# Note: When bumping these numbers, please update the following comments, so
#       it doesn't get double-bumped.
#
LIBCURRENT  = 15
LIBAGE      = 0
LIBREVISION = 0

LIBTOOL=@LIBTOOL@
LIBTOOLCC=$(LIBTOOL) --mode=compile $(CC) $(CFLAGS) $(CPPFLAGS)
LIBTOOLLD=$(LIBTOOL) --mode=link $(CC) $(CFLAGS) -rpath $(libdir) -version-info $(LIBCURRENT):$(LIBREVISION):$(LIBAGE)
LIBTOOLIN=$(LIBTOOL) --mode=install $(INSTALL)
LIBTOOLFN=$(LIBTOOL) --mode=finish
