#!/usr/bin/perl
#
# Copyright 2013 SPARTA, Inc.  All rights reserved.  See the COPYING
# file distributed with this software for details.
#
# owl-data.pod						Owl Monitoring System
#
#       This module contains contains the pod describing the data file
#	name extensions.
#
# Revision History:
#	1.0	130717	Initial version.
#

1;


=pod

=head1 NAME

File name extensions for Owl data files

=head1 DESCRIPTION

This is a list of the file extensions used for Owl data files.

    .dns           owl-dnstimer
    .rrec          owl-rrdata
    .rrsec         owl-rrsec
    .rsrc          owl-resources

=head1 SEE ALSO

B<owl-dnstimer(1)>,
B<owl-resources(1)>,
B<owl-rrdata(1)>,
B<owl-rrsec(1)>

=head1 COPYRIGHT

Copyright 2013 SPARTA, Inc.  All rights reserved.

=head1 AUTHOR

Wayne Morrison, tewok@tislabs.com

=cut
