#!/usr/bin/perl

use Net::DNS::SEC::Tools::conf;
use Net::DNS::SEC::Tools::TrustAnchor;
use Net::DNS::SEC::Tools::QWPrimitives;
use strict;

my %opts;

#
# Perform some housekeeping if we're running packed.
#	- use the packed DNSSEC-Tools config file
#	- make sure the packed ParserDetails.ini file is where XML::SAX expects
#
if (runpacked()) {

    #
    # Use the packed config file.
    #
    setconffile("$ENV{'PAR_TEMP'}/inc/dnssec-tools.conf");

    #
    # Move the ParserDetails.ini file to its required location.
    #
    if (! -e "$ENV{'PAR_TEMP'}/SAX") {
	use Cwd;

	my $cwd = getcwd;

	chdir($ENV{'PAR_TEMP'});

	if (-e "inc/SAX") {
	    rename("inc/SAX", "SAX");
	}

	chdir($cwd);
    }
}


DTGetOptions(\%opts,
	     ["i|input-file=s",  "Input file(s)"],
	     ["o|output-file=s", "Output file(s)"],
	    ) || exit 1;

my $input_file = $opts{'i'} || shift @ARGV;
my $output_file = $opts{'o'} || shift @ARGV;

my ($mod, $file, $options) = parse_component($input_file);

my $tar = $mod->read();
die "reading tar from $input_file failed\n" if (!$tar);

if ($output_file ne '') {
    my ($mod, $file, $options) = parse_component($output_file);
    return if (!$mod);
    $mod->write($tar, $file);
}

=pod

=head1 NAME

B<convertar> - Converts trust anchor repositories from one format to another

=head1 CONVENTIONS

B<convertar> operates on input and output files of different Trust
Anchor Repository (TAR) formats.  B<convertar> decides what type of
file format is being refered two by a "type:filename" specification.
See below for a list of different input and ouput formats that
convertar understands by default.

See the I<Net::DNS::SEC::Tools::TrustAnchor> module and it's
documentation for writing new plugins to allow convertar to understand
other TAR formats.

=head1 EXAMPLES

This command will read in an itar.xml file (available from
https://itar.iana.org/) and convert it to a file that can be read in
by bind's named application:

  # convertar -i itar:itar.xml -o bind:bind.conf

=head1 FILE FORMATS

The following file formats are known by default to convertar:

=over

=item bind

A I<bind> name server (named) compatible trust anchor configuration file.
This can be included within a master named.conf file using the
"include" directive.

=item csv

A comma separated list format.

=item dump

A perl hash I<dump> format.  This should be used mostly for debugging of
newly developed moudles as it shows the interal hash structure that is
passed between modules.

=item itar

IANA's <itar> format, which is a XML-based format of trust anchor
keys.  IANA's file is available from https://itar.iana.org/.

=item libval

The I<libval> format is the configuration file format that that
DNSSEC-Tool's libval library uses.

=item mf

The master file (I<mf>) format is also available from the I<itar> web
site.

=back

=head1 OPTIONS

=item  -i STRING

=item  --input-file=STRING

Input file(s) to process.

B<convertar> will read in the specified file(s).  Multiple files can
be separated by commas.

=item  -o STRING

=item  --output-file=STRING

Output file(s) to write.

B<convertar> will write out these specified file(s) in the requested
output formats.  Multiple files can be separated by commas.

=item -h

=item --help

=item --help-full

Displays command line help information.

=item --gui

=item --no-gui

Controls the display of the optional GUI.

=cut

