.TH DNSSEC_TOOLS 1 "5 Dec 2007" "DNSSEC-Tools"
.UC 5
.SH NAME
DNSSEC-Tools \- A suite of tools and libraries for using DNSSEC
.SH DESCRIPTION
The DNSSEC-Tools package contains a wide variety of tools that are
helpful to zone operators, resolver operators, network operators,
application developers and end-users of DNSSEC.
.PP
The best place to learn about the tools that are part of the package
is at the following website, which categorizes the tools according to
the intended audience:
.IP
http://www.dnssec-tools.org/wiki/index.php/DNSSEC-Tools_Components
.PP
Additionally, make sure to check out the tutorials available at:
.IP
http://www.dnssec-tools.org/wiki/index.php/Tutorials
.SH "LICENSE"
The DNSSEC-Tools are licensed under a BSD license, the details of
which can be found in the COPYING file found within the distribution.

