#!/usr/bin/perl
# Copyright 2004-2007 SPARTA, Inc.  All rights reserved.
# See the COPYING file included with the DNSSEC-Tools package for details.

use IO::Socket::INET;
use IO::File;
use Getopt::Long;
use Net::DNS::SEC::Tools::conf;
use Net::DNS::SEC::Tools::BootStrap;

######################################################################
# detect needed GraphViz requirement
#
dnssec_tools_load_mods('GraphViz' => "");

########################################################
# Globals

my $gv;
my $name;
my $class; 
my $type;
my $status;
my $dest;
my $i;
my $socket;
my $count;
my $edge_str;
my $giffile;
my $htmlfile;
my $htmlfh;
my $giftmp;

########################################################
# Defaults

my %opts = (
	h => "127.0.0.1",
	p => "1053",
	f => "val_log_map.html",
	g => "val_log_map.gif",
	r => 5,
	s => 0,
	d => 0
);


########################################################
# main

# Parse command-line options
GetOptions(\%opts, "d=s", "p=s", "f=s", "g=s", "r=i", "s");

# Parse the dnssec-tools.conf file
my %dtconf = parseconfig();

$gv = GraphViz->new(rankdir => 1, edge => { fontsize => '9'});
$count = 0;
$newnode = "";
$curnode = "";
$giffile = $opts{'g'};
$htmlfile = $opts{'f'};
$refresh = $opts{'r'};
# create an HTML file with the image and 
# with auto refresh set to 5 seconds
$htmlfh = new IO::File(">$htmlfile");
print $htmlfh "<html>\n<head>\n".
	"<title>Validator Results</title>\n".
	"<meta http-equiv=\"refresh\" content=\"$refresh\">\n".
	"</head>\n".
	"<body> <img src=\"$giffile\" alt=\"Validator Status\"> </body>\n".
	"</html>";
$htmlfh->close;


# check if socket operation is desired
if($opts{'s'} == 1) {
	$local_host = $opts{'d'};
	$local_port = $opts{'p'};
	$socket = IO::Socket::INET->new(LocalAddr => $local_host,
                                LocalPort => $local_port,
                                Proto    => "udp",
                                Type     => SOCK_DGRAM)
    	or die "Couldn't bind to $local_host:$local_port\n";

	while ($_=<$socket>) {
		update_image($_);
	}

	# Never reached
	close($socket);
}


# Read from stdin
while ($_=<STDIN>) {
	update_image($_);
}

#
# End Main
########################################################

########################################################
# 
# update the graph and store as a gif 
#
sub update_image {

    # Look for only messages of the following type
    if (/\s*name=(\S+)\s*class=(\S+)\s*type=(\S+)\s*from-server=(\S+)\s*status=(\S+):/) {
        ($name, $class, $type, $dest, $status) = ($1, $2, $3, $4, $5); 
        #$log[$count] =  "$1 $2 $3 $4 $5" ;
        #$edge_str = $name . ":" . $class . ":" . $type . ":" . "$status" ;
        $log[$count] =  "$4 $5" ;
        $edge_str = $status ;
       	$newnode = $dest;
	}
	else {
	    # received data that this utility has no use for
	    return;
	}

	# remove duplicates from the array so that 
	# all edges on the graph are different
	my %hash = map { $_, 1 } @log;
	@log = keys %hash;

	# Check if something new was added 
	if($count == ($#log + 1)) {
		return;
	}

	$count = $#log + 1;

	# add the node and an edge from the Validator
    if ($curnode ne $newnode) { 
        if ($curnode eq "") {
            $curnode = "libval";
        }
		$gv->add_node($newnode);
        $gv->add_edge($curnode, $newnode, label => $edge_str, decorateP => '1', get_ac_lineattr($status));
		# update the image only when something has changed
		$giftmp = $giffile . "tmp"; 
		# generate the gif file
		$gv->as_gif($giftmp);
		rename($giftmp, $giffile);
    } 
}

#############################################################
# get the edge properties based on the error status passed as 
# the parameter
#
sub get_ac_lineattr {

	my %prop;
	my $ac_status;
	$ac_status = shift;

	$prop{'dir'} = 'back';

    if (($ac_status eq "VAL_AC_TRUST_KEY") ||
        ($ac_status eq "VAL_AC_VERIFIED")) {

		$prop{'color'} =  "green";
		$prop{'fillcolor'} =  "green";

    } elsif (($ac_status eq "VAL_AC_IGNORE_VALIDATION") ||
        ($ac_status eq "VAL_AC_TRUSTED_ZONE") ||
        ($ac_status eq "VAL_AC_PROVABLY_UNSECURE") ||
        ($ac_status eq "VAL_AC_LOCAL_ANSWER")) {

		$prop{'color'} =  "yellow";
		$prop{'fillcolor'} =  "yellow";

    } elsif (($ac_status eq "VAL_AC_UNTRUSTED_ZONE") ||
        ($ac_status eq "VAL_AC_NOT_VERIFIED") ||
        ($ac_status eq "VAL_AC_NO_TRUST_ANCHOR")) { 

		$prop{'color'} =  "red";
		$prop{'fillcolor'} =  "red";

    } elsif  (($ac_status eq "VAL_AC_RRSIG_MISSING") ||
        ($ac_status eq "VAL_AC_DNSKEY_MISSING") ||
        ($ac_status eq "VAL_AC_DS_MISSING") ||
        ($ac_status eq "VAL_AC_DATA_MISSING") ||
        ($ac_status eq "VAL_AC_BARE_RRSIG")) { 

		$prop{'color'} =  "red";
		$prop{'fillcolor'} =  "red";
		$prop{'style'} = 'dashed';

    } elsif (($ac_status eq "VAL_AC_UNSET") ||
        ($ac_status eq "VAL_AC_UNKNOWN_DNSKEY_PROTOCOL")){

		$prop{'color'} =  "black";
		$prop{'fillcolor'} =  "black";
		$prop{'style'} = 'dashed';
    } 
    else { 
        # other errors
		$prop{'color'} =  "black";
		$prop{'fillcolor'} =  "black";
    } 
    

	return %prop;
}

#############################################################
# get the edge properties based on the error status passed as 
# the parameter
#
sub get_valstatus_lineattr {

	my %prop;
	my $val_status;
	$val_status = shift;

	$prop{'dir'} = 'back';

	if (($val_status eq "VAL_SUCCESS") ||
		($val_status eq "VAL_NONEXISTENT_NAME")||
		($val_status eq "VAL_NONEXISTENT_TYPE") ||
		($val_status eq "VAL_VALIDATED_ANSWER")) {
		$prop{'color'} =  "green";
		$prop{'fillcolor'} =  "green";
		$prop{'style'} = 'bold';
	} 
    elsif (($val_status eq "VAL_PROVABLY_UNSECURE") ||
		   ($val_status eq "VAL_IGNORE_VALIDATION") ||
		   ($val_status eq "VAL_TRUSTED_ZONE") ||
		   ($val_status eq "VAL_TRUSTED_ANSWER") ||
		   ($val_status eq "VAL_NONEXISTENT_NAME_NOCHAIN")||
		   ($val_status eq "VAL_NONEXISTENT_TYPE_NOCHAIN")||
		   ($val_status eq "VAL_LOCAL_ANSWER")) {
		$prop{'color'} =  "yellow";
		$prop{'fillcolor'} =  "yellow";
		$prop{'style'} = 'bold';
    }
	elsif (($val_status eq "VAL_BOGUS_PROVABLE") ||
		   ($val_status eq "VAL_BOGUS_UNPROVABLE") ||
		   ($val_status eq "VAL_UNTRUSTED_ANSWER") ||
		   ($val_status eq "VAL_UNTRUSTED_ZONE") ||
		   ($val_status eq "VAL_BAD_PROVABLY_UNSECURE")||
		   ($val_status eq "VAL_NOTRUST")){
		$prop{'color'} = "red";
		$prop{'fillcolor'} =  "red";
		$prop{'style'} = 'bold';
	} 
	elsif (($val_status eq "VAL_DONT_KNOW") ||
			($val_status eq "VAL_INDETERMINATE") ||
			($val_status eq "VAL_BARE_RRSIG")) {
		$prop{'color'} =  "black";
		$prop{'fillcolor'} =  "black";
		$prop{'style'} = 'dashed';
	} 
	else {
		# errors 
		$prop{'color'} =  "black";
		$prop{'fillcolor'} =  "black";
		$prop{'style'} = 'bold';
	}

	return %prop;
}


=head1 NAME

drawvalmap - Generate a graphical output of validation status values
             encountered by the validator library.

=head1 SYNOPSIS

drawvalmap 

=head1 DESCRIPTION

drawvalmap is a simple utility that can be used to display the query assertion status 
in a graphical format. The input to this script is a set of log messages that 
can be read either from STDIN or from a socket. The default is to read it from STDIN.
The output is an HTML file containing an image of the various validator authentication chain 
status values. The HTML file auto-refreshes every five seconds so that changes to 
the validator graph can be constantly tracked. The drawvalmap script executes 
in an infinite loop and never returns.  

This script can be started from the command line by typing

bash# drawvalmap

It would not be uncommon to use this script for
troubleshooting purposes in which case output generated by a driver 
program would be "piped" to this script in the manner shown below.

bash# ${LIBVAL}/bin/validate -o5:stdout secure.example.com. | drawvalmap 

In each case the script reads log messages from STDIN, generating
a default HTML file with the name val_log_map.html. The gif containing
the actual validator map has the default name as val_log_map.gif. Both
of these defaults can be modified by using the command-line flags 
described below. 

=head1 OPTIONS

=over

=item -f

This changes the name of .html file to the given value.

=item -g

This changes the name of .gif file to the given value.

=item -r

This changes the refresh period in the HTML file to the given value.

=item -s

This changes the mode of operation to read input from a socket.
The default address and port to which drawvalmap binds is
127.0.0.1:1053 

=item -d

This changes the address to which drawvalmap binds itself to
the specified value. This option takes effect only if the
-s option is also specified.

=item -p

This changes the port to which drawvalmap binds itself to
the specified value. This option takes effect only if the
-s option is also specified.

=back
  

=head1 PRE-REQUISITES

GraphViz

=head1 COPYRIGHT

Copyright 2005 SPARTA, Inc.  All rights reserved.
See the COPYING file included with the DNSSEC-Tools package for details.

=cut


 
